const ROLES = {
  werewolf: {
    id: 'werewolf',
    name: 'Werewolf',
    nameVi: 'Người Sói',
    team: 'werewolf',
    nightOrder: 2,
    hasNightAction: true,
    maxCount: 2,
    emoji: '🐺',
    description: 'Bạn là Người Sói! Hãy nhìn xung quanh để tìm đồng bọn.',
    nightInstruction: 'Người Sói, hãy mở mắt và nhìn nhau.',
    nightClose: 'Người Sói, hãy nhắm mắt lại.',
  },
  minion: {
    id: 'minion',
    name: 'Minion',
    nameVi: 'Tay Sai',
    team: 'werewolf',
    nightOrder: 3,
    hasNightAction: true,
    maxCount: 1,
    emoji: '🦹',
    description: 'Bạn là Tay Sai! Hỗ trợ phe Sói nhưng Sói không biết bạn là ai.',
    nightInstruction: 'Tay Sai, hãy mở mắt. Người Sói hãy giơ tay để Tay Sai nhận biết.',
    nightClose: 'Tay Sai, hãy nhắm mắt lại.',
  },
  seer: {
    id: 'seer',
    name: 'Seer',
    nameVi: 'Tiên tri',
    team: 'village',
    nightOrder: 4,
    hasNightAction: true,
    maxCount: 1,
    emoji: '🔮',
    description: 'Bạn là Tiên tri! Xem bài của một người khác, hoặc 2 bài ở giữa.',
    nightInstruction: 'Tiên tri, hãy mở mắt. Bạn có thể xem bài của một người, hoặc 2 bài ở giữa.',
    nightClose: 'Tiên tri, hãy nhắm mắt lại.',
  },
  robber: {
    id: 'robber',
    name: 'Robber',
    nameVi: 'Tên Trộm',
    team: 'village',
    nightOrder: 5,
    hasNightAction: true,
    maxCount: 1,
    emoji: '🦝',
    description: 'Bạn là Tên Trộm! Đổi bài của bạn với bài của người khác và xem bài mới.',
    nightInstruction: 'Tên Trộm, hãy mở mắt. Bạn có thể lấy bài của một người và cho họ bài cũ của bạn.',
    nightClose: 'Tên Trộm, hãy nhắm mắt lại.',
  },
  troublemaker: {
    id: 'troublemaker',
    name: 'Troublemaker',
    nameVi: 'Kẻ Quậy',
    team: 'village',
    nightOrder: 6,
    hasNightAction: true,
    maxCount: 1,
    emoji: '😈',
    description: 'Bạn là Kẻ Quậy! Đổi bài của hai người khác (không xem).',
    nightInstruction: 'Kẻ Quậy, hãy mở mắt. Bạn có thể hoán đổi bài của hai người khác.',
    nightClose: 'Kẻ Quậy, hãy nhắm mắt lại.',
  },
  drunk: {
    id: 'drunk',
    name: 'Drunk',
    nameVi: 'Người Say',
    team: 'village',
    nightOrder: 7,
    hasNightAction: true,
    maxCount: 1,
    emoji: '🍺',
    description: 'Bạn là Người Say! Đổi bài với bài ở giữa (bạn không biết bài mới của mình).',
    nightInstruction: 'Người Say, hãy mở mắt và chọn một bài ở giữa để hoán đổi. Bạn sẽ không biết bài của mình.',
    nightClose: 'Người Say, hãy nhắm mắt lại.',
  },
  insomniac: {
    id: 'insomniac',
    name: 'Insomniac',
    nameVi: 'Mất Ngủ',
    team: 'village',
    nightOrder: 8,
    hasNightAction: true,
    maxCount: 1,
    emoji: '👁️',
    description: 'Bạn là người Mất Ngủ! Bạn thức dậy cuối cùng và xem bài hiện tại của mình.',
    nightInstruction: 'Người Mất Ngủ, hãy mở mắt và xem bài hiện tại của bạn.',
    nightClose: 'Người Mất Ngủ, hãy nhắm mắt lại.',
  },
  villager: {
    id: 'villager',
    name: 'Villager',
    nameVi: 'Dân Làng',
    team: 'village',
    nightOrder: 99,
    hasNightAction: false,
    maxCount: 3,
    emoji: '👨‍🌾',
    description: 'Bạn là Dân Làng! Không có hành động đặc biệt ban đêm.',
    nightInstruction: null,
    nightClose: null,
  },
  hunter: {
    id: 'hunter',
    name: 'Hunter',
    nameVi: 'Thợ Săn',
    team: 'village',
    nightOrder: 99,
    hasNightAction: false,
    maxCount: 1,
    emoji: '🏹',
    description: 'Bạn là Thợ Săn! Nếu bạn bị loại, người bạn vote cũng bị loại theo.',
    nightInstruction: null,
    nightClose: null,
  },
  tanner: {
    id: 'tanner',
    name: 'Tanner',
    nameVi: 'Kẻ Tự Hủy',
    team: 'tanner',
    nightOrder: 99,
    hasNightAction: false,
    maxCount: 1,
    emoji: '💀',
    description: 'Bạn là Kẻ Tự Hủy! Bạn thắng nếu bị loại khỏi game.',
    nightInstruction: null,
    nightClose: null,
  },
};

// Night order for roles that have actions (excluding passive roles)
const ACTIVE_NIGHT_ROLES = ['werewolf', 'minion', 'seer', 'robber', 'troublemaker', 'drunk', 'insomniac'];

function getNightOrder(selectedRoles) {
  const roleSet = new Set(selectedRoles);
  return ACTIVE_NIGHT_ROLES.filter(r => roleSet.has(r));
}

module.exports = { ROLES, getNightOrder };
